# Generated by Django 2.1.15 on 2020-03-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20)),
                ('tz', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='activity_period',
            name='activity_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dance_app.user'),
        ),
    ]
