# Generated by Django 2.1.15 on 2020-03-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dance_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity_period',
            old_name='activity_period',
            new_name='user',
        ),
    ]
