# Generated by Django 2.1.15 on 2020-03-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dance_app', '0002_auto_20200327_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_period',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_periods', to='dance_app.user'),
        ),
    ]
